defaults: &defaults
  repo_storage_path: <%= Rails.root %>/git_sites
  repo_clone_url: "therabidbanana@localhost:~/gitgrove"
  preview_storage_path: <%= Rails.root %>/site_preview
  archives_path: <%= Rails.root %>/public/site_archives
  oa:
    facebook: nil
  
development:
  <<: *defaults

test:
  <<: *defaults
  repo_storage_path: /tmp/gitgrovesites
  preview_storage_path: /tmp/gitgrovepreview
  archives_path: /tmp/gitgrovesite_archives


production:
  <<: *defaults
  

