defaults: &defaults
  repo_storage_path: <%= Rails.root %>/git_sites
  repo_clone_url: "therabidbanana@gitgrove.dev:~/gitgrove"
  preview_storage_path: <%= Rails.root %>/site_preview
  oa:
    facebook: nil
  
development:
  <<: *defaults

test:
  <<: *defaults
  repo_storage_path: /tmp/gitgrovesites
  preview_storage_path: /tmp/gitgrovepreview


production:
  <<: *defaults

