defaults: &defaults
  repo_storage_path: <%= Rails.root %>/git_sites
  oa:
    facebook: nil
  
development:
  <<: *defaults

test:
  <<: *defaults
  repo_storage_path: /tmp/git_sites

production:
  <<: *defaults

